import { 
  CommodityCategory, 
  DeclarationItem, 
  FingerprintFieldDiff, 
  InspectionRecord, 
  InspectorProfile, 
  LabelTruthFinding, 
  PCRRule, 
  ProductFingerprint, 
  SpectraFinding 
} from '@/types/inspection';

export const CURRENT_INSPECTOR: InspectorProfile = {
  name: 'Rajesh Varma',
  id: 'GOI-LMO-DL-0482',
  designation: 'Legal Metrology Officer (Gazetted)',
  region: 'North Zone — Delhi Regional Directorate',
  office: 'Department of Consumer Affairs, Krishi Bhawan, New Delhi',
  avatarInitials: 'RV',
  activeInspectionsToday: 14,
};

export const PCR_RULES: PCRRule[] = [
  {
    ruleId: 'PCR-R06-1A',
    ruleNumber: 'Rule 6(1)(a)',
    title: 'Generic Name / Common Description of Commodity',
    version: 'PCR 2011 (As Amended 2022)',
    applicability: 'All pre-packaged commodities sold, distributed, or delivered in India.',
    summary: 'The common or generic name of the commodity must be prominently declared on the principal display panel.',
    fullClauseText: 'Every package shall bear thereon or on label securely affixed thereto the name and address of the manufacturer or where the manufacturer is not the packer, the name and address of the manufacturer and packer and for any package imported into India, the name and address of the importer.',
    mandatoryEvidence: 'High-resolution image of the Principal Display Panel (PDP) showing unambiguous generic nomenclature.',
    penaltySection: 'Section 36(1) of Legal Metrology Act, 2009 — Fine up to ₹25,000 for first offence, ₹50,000 for second offence.',
    status: 'Mandatory',
  },
  {
    ruleId: 'PCR-R06-1B',
    ruleNumber: 'Rule 6(1)(b)',
    title: 'Net Quantity Declaration in Standard Units of Mass/Measure',
    version: 'PCR 2011 (As Amended 2022)',
    applicability: 'All packaged commodities with quantifiable weight, measure, or numerical count.',
    summary: 'Net quantity must be declared in standard SI metric units (g, kg, ml, L) or numerical count with minimum font height.',
    fullClauseText: 'The net quantity, in terms of the standard unit of weight or measure, of the commodity contained in the package or where the commodity is packed or sold by number, the number of the commodity contained in the package shall be mentioned.',
    mandatoryEvidence: 'Cropped snippet of Net Quantity area and letter height verification against package area schedule.',
    penaltySection: 'Section 36(2) of Legal Metrology Act, 2009 — Fine up to ₹50,000 or imprisonment up to 1 year for repeat offences.',
    status: 'Mandatory',
  },
  {
    ruleId: 'PCR-R06-1C',
    ruleNumber: 'Rule 6(1)(c)',
    title: 'Maximum Retail Price (MRP) Declaration (Inclusive of All Taxes)',
    version: 'PCR 2011 (As Amended 2022)',
    applicability: 'All retail pre-packaged commodities.',
    summary: 'Retail sale price must be declared in Indian Rupees as "MRP ₹ xx.xx (inclusive of all taxes)" without alteration, overwriting, or dual stickers.',
    fullClauseText: 'The retail sale price of the package shall be clearly printed, showing maximum retail price inclusive of all taxes in the form MRP Rs. ... incl. of all taxes.',
    mandatoryEvidence: 'Multi-view inspection crops showing absence of dual pricing or sticker overwrites.',
    penaltySection: 'Section 36(1) read with Rule 18(2) — Fine up to ₹25,000; compounding or prosecution for overcharging.',
    status: 'Mandatory',
  },
  {
    ruleId: 'PCR-R06-1E',
    ruleNumber: 'Rule 6(1)(e)',
    title: 'Mandatory Unit Sale Price (USP) for Packages > 100g / 100ml',
    version: 'Amended Gazette Notification G.S.R. 779(E) (w.e.f. Dec 2022)',
    applicability: 'All packaged commodities where net quantity is not exactly 1 kg, 1 litre, or 1 unit.',
    summary: 'Unit Sale Price (e.g. ₹/g, ₹/kg, ₹/ml) must be declared adjacent to MRP rounded off to two decimal places.',
    fullClauseText: 'For packages containing more than one kilogram or one litre, the unit sale price shall be declared in terms of per kilogram or per litre; for packages under 1kg/1L, per gram or per millilitre.',
    mandatoryEvidence: 'OCR extraction of unit rate adjacent to MRP with calculation cross-check.',
    penaltySection: 'Rule 32 — Non-declaration penalty up to ₹25,000.',
    status: 'Amended (2022)',
  },
  {
    ruleId: 'PCR-R06-1D',
    ruleNumber: 'Rule 6(1)(d)',
    title: 'Month and Year of Manufacture / Packing / Import',
    version: 'PCR 2011',
    applicability: 'All pre-packaged commodities except exempt bulk agricultural products.',
    summary: 'Month and year in which commodity is manufactured, packed, or imported must be legibly printed.',
    fullClauseText: 'The month and year in which the commodity is manufactured or pre-packed or imported shall be mentioned in letters and numerals.',
    mandatoryEvidence: 'Batch coding or ink-jet timestamp verification on seal crimp or bottom panel.',
    penaltySection: 'Section 36(1) — Fine up to ₹25,000.',
    status: 'Mandatory',
  },
  {
    ruleId: 'PCR-R06-1F',
    ruleNumber: 'Rule 6(1)(f)',
    title: 'Country of Origin Declaration',
    version: 'Gazette Notification 2020 Amendment',
    applicability: 'All imported as well as domestically manufactured pre-packaged goods.',
    summary: 'Country of origin or place of manufacture must be clearly declared on the PDP or back label.',
    fullClauseText: 'The name of the country of origin or manufacture or assembly in the case of imported products shall be declared explicitly.',
    mandatoryEvidence: 'Origin declaration token extraction ("Made in India", "Country of Origin: ...").',
    penaltySection: 'Section 36(1) of Legal Metrology Act, 2009.',
    status: 'Mandatory',
  },
  {
    ruleId: 'PCR-R06-1G',
    ruleNumber: 'Rule 6(1)(g)',
    title: 'Consumer Care & Grievance Redressal Cell Information',
    version: 'PCR 2011',
    applicability: 'All consumer packaged commodities.',
    summary: 'Name, address, telephone number, and email address of person/office for consumer complaints must be provided.',
    fullClauseText: 'Every package shall bear name, address, telephone number and e-mail address of the person who can be or the office which can be contacted in case of consumer complaints.',
    mandatoryEvidence: 'Verification of helpline number format, email domain, and consumer care address.',
    penaltySection: 'Rule 32 & Section 36(1).',
    status: 'Mandatory',
  },
  {
    ruleId: 'PCR-R09',
    ruleNumber: 'Rule 9 / Schedule II',
    title: 'Manner of Declaration & Minimum Numeral/Letter Height',
    version: 'PCR 2011',
    applicability: 'All pre-packaged labels based on Principal Display Panel area.',
    summary: 'Minimum letter and numeral heights must conform to Schedule II (e.g. 2mm to 6mm depending on package area) to prevent deceptive shrink print.',
    fullClauseText: 'The minimum height of any numeral and letter in the declaration shall be as specified in Table I of Schedule II.',
    mandatoryEvidence: 'Pixel-to-millimeter calibrated font scale measurement from label close-up.',
    penaltySection: 'Section 36(1) of Legal Metrology Act, 2009.',
    status: 'Active',
  },
  {
    ruleId: 'PCR-R18-2',
    ruleNumber: 'Rule 18(2)',
    title: 'Prohibition Against Dual MRP / Affixing Alternate Price Stickers',
    version: 'PCR 2011',
    applicability: 'All retail packages.',
    summary: 'No wholesale dealer, retail dealer or other person shall obliterate, smudge or alter retail sale price or charge price higher than MRP.',
    fullClauseText: 'No person shall alter, obliterate or smudge the retail sale price printed on the package or sell at a price higher than the retail sale price indicated on the package.',
    mandatoryEvidence: 'Multi-view comparison demonstrating sticker overlay or conflicting printed values.',
    penaltySection: 'Section 36(1) read with Section 53 — Penalty and liability for criminal prosecution.',
    status: 'Mandatory',
  }
];

export const SAMPLE_PRODUCTS: Record<string, InspectionRecord> = {
  'SAMPLE-FONTSIZE': {
    id: 'INSP-2026-FNT-998',
    date: '2026-09-06',
    timestamp: '11:15:30 IST',
    inspectorName: 'Rajesh Varma',
    inspectorId: 'GOI-LMO-DL-0482',
    inspectorRegion: 'North Zone — Delhi',
    productName: 'Organic Green Tea 250g',
    brand: 'Tea Co Ltd.',
    sku: 'SKU-FNT-001',
    barcode: '8901234567891',
    category: 'Food & Beverages',
    overallStatus: 'FAIL',
    overallScore: 72,
    sampleImages: {
      front: '/images/front_dual_mrp.jpeg',
      back: '/images/back_dual_mrp.jpeg',
    },
    declarations: [
      {
        id: 'DEC-FNT-01',
        field: 'Maximum Retail Price (MRP)',
        hindiLabel: 'अधिकतम खुदरा मूल्य',
        pcrRuleClause: 'Rule 9 & Schedule II',
        extractedValue: '₹ 250.00 (Numeral Height: 1.2 mm)',
        standardRequirement: 'Minimum numeral height 2.0 mm for package area 200–500 cm²',
        confidence: 95,
        status: 'FAIL',
        viewSource: 'Back View',
        isMandatory: true,
        inspectorNote: 'VIOLATION: MRP numeral height is 1.2 mm. Rule 9 requires a minimum height of 2.0 mm for packages of this area.',
      },
      {
        id: 'DEC-FNT-02',
        field: 'Net Quantity',
        hindiLabel: 'शुद्ध मात्रा',
        pcrRuleClause: 'Rule 6(1)(b) & Rule 9',
        extractedValue: '250 g (Numeral Height: 2.2 mm)',
        standardRequirement: 'Minimum numeral height 2.0 mm',
        confidence: 98,
        status: 'PASS',
        viewSource: 'Front View',
        isMandatory: true,
      },
      {
        id: 'DEC-FNT-03',
        field: 'Date of Manufacture',
        hindiLabel: 'निर्माण की तारीख',
        pcrRuleClause: 'Rule 6(1)(d)',
        extractedValue: '01/2026',
        standardRequirement: 'Month and Year of manufacture',
        confidence: 92,
        status: 'PASS',
        viewSource: 'Back View',
        isMandatory: true,
      },
      {
        id: 'DEC-FNT-04',
        field: 'Manufacturer Details',
        hindiLabel: 'निर्माता का नाम व पता',
        pcrRuleClause: 'Rule 6(1)(a)',
        extractedValue: 'Tea Co Ltd., Assam, India',
        standardRequirement: 'Name and complete address of the manufacturer',
        confidence: 89,
        status: 'PASS',
        viewSource: 'Back View',
        isMandatory: true,
      },
      {
        id: 'DEC-FNT-05',
        field: 'Consumer Care Details',
        hindiLabel: 'उपभोक्ता सेवा विवरण',
        pcrRuleClause: 'Rule 6(1)(g)',
        extractedValue: '1800-123-456 | care@teaco.in',
        standardRequirement: 'Consumer helpline telephone and email',
        confidence: 91,
        status: 'PASS',
        viewSource: 'Back View',
        isMandatory: true,
      },
    ],
    labelTruthFindings: [
      {
        id: 'lt-fnt-01',
        field: 'Numeral & Letter Height Compliance',
        viewA: {
          name: 'Front Principal Display Area',
          value: 'Net Qty: 2.2 mm (Compliant)',
          confidence: 96,
        },
        viewB: {
          name: 'Back Information Panel',
          value: 'MRP: 1.2 mm (Non-Compliant, Min 2.0 mm required)',
          confidence: 98,
        },
        status: 'INCONSISTENT',
        confidence: 98,
        ruleReference: 'Rule 9 & Schedule II (Height of Numerals and Letters)',
        legalExplanation: 'Rule 9 prescribes mandatory minimum numeral heights depending on the principal display panel area. The declared MRP numeral height (1.2 mm) falls below the statutory threshold of 2.0 mm.',
        recommendedAction: 'Issue compounding notice under Section 36(1) of Legal Metrology Act for sub-standard typography.',
      },
    ],
  },

  'SAMPLE-COMPLIANT': {
    id: 'INSP-2026-08491',
    date: '2026-09-05',
    timestamp: '14:22:10 IST',
    inspectorName: 'Rajesh Varma',
    inspectorId: 'GOI-LMO-DL-0482',
    inspectorRegion: 'North Zone — Delhi',
    productName: 'Shaktibhog Chakki Fresh Atta',
    brand: 'Shaktibhog',
    sku: 'SB-AT-5KG-01',
    barcode: '8901234567890',
    category: 'Packaged Staples',
    overallStatus: 'PASS',
    overallScore: 98,
    sampleImages: {
      front: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=800&q=80',
      back: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80',
      side: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
      labelCloseUp: 'https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&w=800&q=80',
    },
    declarations: [
      {
        id: 'DEC-01',
        field: 'Generic Name',
        hindiLabel: 'सामान्य नाम',
        pcrRuleClause: 'Rule 6(1)(a)',
        extractedValue: 'Whole Wheat Atta (100% Chakki Fresh)',
        standardRequirement: 'Must clearly state generic nomenclature on PDP',
        confidence: 99,
        status: 'PASS',
        viewSource: 'Front View',
        isMandatory: true,
        boundingBox: { x: 22, y: 18, width: 56, height: 12 },
        inspectorNote: 'Prominently visible on front display panel; letters > 6mm.',
      },
      {
        id: 'DEC-02',
        field: 'Net Quantity',
        hindiLabel: 'शुद्ध मात्रा',
        pcrRuleClause: 'Rule 6(1)(b)',
        extractedValue: '5 kg (5.000 kg)',
        standardRequirement: 'Standard metric unit (kg) in approved numeral height',
        confidence: 98,
        status: 'PASS',
        viewSource: 'Front View',
        isMandatory: true,
        boundingBox: { x: 68, y: 76, width: 24, height: 10 },
        inspectorNote: 'Declared in standard SI unit; matches gravimetric check threshold.',
      },
      {
        id: 'DEC-03',
        field: 'Maximum Retail Price (MRP)',
        hindiLabel: 'अधिकतम खुदरा मूल्य',
        pcrRuleClause: 'Rule 6(1)(c)',
        extractedValue: '₹ 210.00 (Incl. of all taxes)',
        standardRequirement: '₹ symbol + value + "incl. of all taxes"',
        confidence: 96,
        status: 'PASS',
        viewSource: 'Back View',
        isMandatory: true,
        boundingBox: { x: 15, y: 35, width: 38, height: 8 },
        inspectorNote: 'Clear non-smudged print; tax inclusivity statement present.',
      },
      {
        id: 'DEC-04',
        field: 'Unit Sale Price (USP)',
        hindiLabel: 'इकाई विक्रय मूल्य',
        pcrRuleClause: 'Rule 6(1)(e)',
        extractedValue: '₹ 42.00 / kg',
        standardRequirement: 'Mandatory adjacent to MRP under Dec 2022 notification',
        confidence: 97,
        status: 'PASS',
        viewSource: 'Back View',
        isMandatory: true,
        boundingBox: { x: 15, y: 44, width: 32, height: 7 },
        inspectorNote: 'Accurately calculated (₹210 / 5kg = ₹42/kg). Complies with GSR 779(E).',
      },
      {
        id: 'DEC-05',
        field: 'Manufacturer & Packer Details',
        hindiLabel: 'निर्माता एवं पैकर विवरण',
        pcrRuleClause: 'Rule 6(1)(a)',
        extractedValue: 'Shaktibhog Agro Foods Ltd., Plot 14, Okhla Ind. Area Phase-III, New Delhi - 110020',
        standardRequirement: 'Complete registered premises address with PIN code',
        confidence: 95,
        status: 'PASS',
        viewSource: 'Back View',
        isMandatory: true,
        boundingBox: { x: 12, y: 55, width: 75, height: 16 },
        inspectorNote: 'Complete postal address verified against MCA company registry.',
      },
      {
        id: 'DEC-06',
        field: 'Month & Year of Packing',
        hindiLabel: 'पैकिंग का माह एवं वर्ष',
        pcrRuleClause: 'Rule 6(1)(d)',
        extractedValue: 'PKD: AUG 2026 | BATCH: SBF-268A',
        standardRequirement: 'Legible month and year in numerals/words',
        confidence: 94,
        status: 'PASS',
        viewSource: 'Back View',
        isMandatory: true,
        boundingBox: { x: 55, y: 35, width: 35, height: 9 },
      },
      {
        id: 'DEC-07',
        field: 'Country of Origin',
        hindiLabel: 'मूल देश',
        pcrRuleClause: 'Rule 6(1)(f)',
        extractedValue: 'Country of Origin: India',
        standardRequirement: 'Mandatory declaration of origin country',
        confidence: 98,
        status: 'PASS',
        viewSource: 'Back View',
        isMandatory: true,
        boundingBox: { x: 12, y: 73, width: 40, height: 6 },
      },
      {
        id: 'DEC-08',
        field: 'Consumer Care Redressal',
        hindiLabel: 'उपभोक्ता सेवा विवरण',
        pcrRuleClause: 'Rule 6(1)(g)',
        extractedValue: 'Toll-Free: 1800-11-4567 | customercare@shaktibhog.com | DCA Grievance Cell',
        standardRequirement: 'Working phone number + email + physical address',
        confidence: 93,
        status: 'PASS',
        viewSource: 'Back View',
        isMandatory: true,
        boundingBox: { x: 12, y: 81, width: 78, height: 12 },
      }
    ],
    qrVerified: true,
  },

  'SAMPLE-LABELTRUTH': {
    id: 'INSP-2026-08492',
    date: '2026-09-05',
    timestamp: '14:38:45 IST',
    inspectorName: 'Rajesh Varma',
    inspectorId: 'GOI-LMO-DL-0482',
    inspectorRegion: 'North Zone — Delhi',
    productName: 'Crispy Munch Butter Gold Biscuits',
    brand: 'Crispy Munch',
    sku: 'CM-BG-200G',
    barcode: '8906012398471',
    category: 'Food & Beverages',
    overallStatus: 'FAIL',
    overallScore: 64,
    sampleImages: {
      front: '/images/front_dual_mrp.jpeg',
      back: '/images/back_dual_mrp.jpeg',
    },
    declarations: [
      {
        id: 'DEC-11',
        field: 'Generic Name',
        hindiLabel: 'सामान्य नाम',
        pcrRuleClause: 'Rule 6(1)(a)',
        extractedValue: 'Butter Biscuits (Gold Baked)',
        standardRequirement: 'Generic designation on PDP',
        confidence: 98,
        status: 'PASS',
        viewSource: 'Front View',
        isMandatory: true,
      },
      {
        id: 'DEC-12',
        field: 'Net Quantity',
        hindiLabel: 'शुद्ध मात्रा',
        pcrRuleClause: 'Rule 6(1)(b)',
        extractedValue: '200 g',
        standardRequirement: 'Metric declaration with letter height > 3mm',
        confidence: 96,
        status: 'PASS',
        viewSource: 'Front View',
        isMandatory: true,
      },
      {
        id: 'DEC-13',
        field: 'Maximum Retail Price (MRP)',
        hindiLabel: 'अधिकतम खुदरा मूल्य',
        pcrRuleClause: 'Rule 6(1)(c) & Rule 18(2)',
        extractedValue: 'Front Sticker: ₹ 10.00 vs Back Label: ₹ 9.00',
        standardRequirement: 'Uniform, non-conflicting MRP without promotional sticker mark-up',
        confidence: 96,
        status: 'FAIL',
        viewSource: 'Front View',
        isMandatory: true,
        inspectorNote: 'CRITICAL: Sticker overlay on front panel shows ₹10 whereas original manufacturer pre-printed back panel declares ₹9. Dual MRP Violation under Rule 18(2).',
      },
      {
        id: 'DEC-14',
        field: 'Unit Sale Price (USP)',
        hindiLabel: 'इकाई विक्रय मूल्य',
        pcrRuleClause: 'Rule 6(1)(e)',
        extractedValue: 'Not Declared (Missing)',
        standardRequirement: 'Mandatory ₹/g or ₹/kg declaration adjacent to MRP',
        confidence: 92,
        status: 'FAIL',
        viewSource: 'Back View',
        isMandatory: true,
        inspectorNote: 'Unit Sale Price missing from both front promotional sticker and back legal panel.',
      },
      {
        id: 'DEC-15',
        field: 'Manufacturer & Packer',
        hindiLabel: 'निर्माता विवरण',
        pcrRuleClause: 'Rule 6(1)(a)',
        extractedValue: 'ABC Confectionery Ltd., Industrial Estate, Baddi, HP - 173205',
        standardRequirement: 'Registered address',
        confidence: 94,
        status: 'PASS',
        viewSource: 'Back View',
        isMandatory: true,
      },
      {
        id: 'DEC-16',
        field: 'Month & Year of Packing',
        hindiLabel: 'पैकिंग तिथि',
        pcrRuleClause: 'Rule 6(1)(d)',
        extractedValue: '07/2026',
        standardRequirement: 'Month and year declared',
        confidence: 93,
        status: 'PASS',
        viewSource: 'Back View',
        isMandatory: true,
      }
    ],
    labelTruthFindings: [
      {
        id: 'LT-01',
        field: 'Maximum Retail Price (MRP)',
        viewA: {
          name: 'Front Promotional Area',
          value: '₹ 10.00',
          confidence: 97,
        },
        viewB: {
          name: 'Back Regulatory Panel',
          value: '₹ 9.00',
          confidence: 95,
        },
        status: 'INCONSISTENT',
        confidence: 96,
        ruleReference: 'Rule 18(2) & Section 36(1) of Legal Metrology Act, 2009',
        legalExplanation: 'Dual MRP or selling at a rate higher than the printed MRP is an offence under Rule 18(2). Cross-view image crop analysis confirms that an unauthorized retail price sticker has inflated the effective retail price by ₹1.00.',
        recommendedAction: 'Issue statutory Show-Cause Notice under Form LM-1 and impound representative test batch.',
      }
    ]
  },

  'SAMPLE-ACTIVE-INSPECTION': {
    id: 'INSP-2026-08493',
    date: '2026-09-05',
    timestamp: '14:55:02 IST',
    inspectorName: 'Rajesh Varma',
    inspectorId: 'GOI-LMO-DL-0482',
    inspectorRegion: 'North Zone — Delhi',
    productName: 'NutriPure Kachi Ghani Mustard Oil',
    brand: 'NutriPure',
    sku: 'NP-MO-1L',
    barcode: '8904561230094',
    category: 'Edible Oils & Fats',
    overallStatus: 'REVIEW',
    overallScore: 71,
    activeInspectionRequired: true,
    uncertainFieldId: 'DEC-23',
    sampleImages: {
      front: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=800&q=80',
      back: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=800&q=80',
      side: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80',
      labelCloseUp: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
    },
    declarations: [
      {
        id: 'DEC-21',
        field: 'Generic Name',
        hindiLabel: 'सामान्य नाम',
        pcrRuleClause: 'Rule 6(1)(a)',
        extractedValue: 'Kachi Ghani Mustard Oil (Cold Pressed)',
        standardRequirement: 'Generic name on PDP',
        confidence: 97,
        status: 'PASS',
        viewSource: 'Front View',
        isMandatory: true,
      },
      {
        id: 'DEC-22',
        field: 'Net Quantity',
        hindiLabel: 'शुद्ध मात्रा',
        pcrRuleClause: 'Rule 6(1)(b)',
        extractedValue: '1 Litre (910 g equivalent at 30°C)',
        standardRequirement: 'Volumetric and mass equivalent declared for edible oils',
        confidence: 95,
        status: 'PASS',
        viewSource: 'Front View',
        isMandatory: true,
      },
      {
        id: 'DEC-23',
        field: 'Maximum Retail Price (MRP)',
        hindiLabel: 'अधिकतम खुदरा मूल्य',
        pcrRuleClause: 'Rule 6(1)(c)',
        extractedValue: '₹ 1??.?? (Partial Glare detected)',
        standardRequirement: 'Legible uninterrupted MRP without flare or reflections',
        confidence: 42,
        status: 'REVIEW',
        viewSource: 'Back View',
        isMandatory: true,
        inspectorNote: 'Uncertain region: Light glare and transparent bottle curvature prevent high-confidence OCR extraction. Active re-capture recommended.',
      },
      {
        id: 'DEC-24',
        field: 'Country of Origin',
        hindiLabel: 'मूल देश',
        pcrRuleClause: 'Rule 6(1)(f)',
        extractedValue: 'Text obscured by bottle curvature',
        standardRequirement: 'Mandatory declaration',
        confidence: 48,
        status: 'REVIEW',
        viewSource: 'Back View',
        isMandatory: true,
      },
      {
        id: 'DEC-25',
        field: 'Unit Sale Price',
        hindiLabel: 'इकाई विक्रय मूल्य',
        pcrRuleClause: 'Rule 6(1)(e)',
        extractedValue: '₹ 175.00 / Litre (Extracted from secondary tag)',
        standardRequirement: 'Mandatory USP',
        confidence: 88,
        status: 'PASS',
        viewSource: 'Side View',
        isMandatory: true,
      }
    ]
  },

  'SAMPLE-FINGERPRINT': {
    id: 'INSP-2026-08494',
    date: '2026-09-05',
    timestamp: '15:10:30 IST',
    inspectorName: 'Rajesh Varma',
    inspectorId: 'GOI-LMO-DL-0482',
    inspectorRegion: 'North Zone — Delhi',
    productName: 'Herbal Glow Ayurvedic Anti-Dandruff Shampoo',
    brand: 'Herbal Glow',
    sku: 'HG-SH-350ML',
    barcode: '8907890123456',
    category: 'Personal Care & Cosmetics',
    overallStatus: 'REVIEW',
    overallScore: 82,
    sampleImages: {
      front: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=800&q=80',
      back: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
      side: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=800&q=80',
      labelCloseUp: 'https://images.unsplash.com/photo-1585751119414-ef2636f8aede?auto=format&fit=crop&w=800&q=80',
    },
    declarations: [
      {
        id: 'DEC-31',
        field: 'Generic Name',
        hindiLabel: 'सामान्य नाम',
        pcrRuleClause: 'Rule 6(1)(a)',
        extractedValue: 'Herbal Shampoo with Neem & Tea Tree',
        standardRequirement: 'Generic declaration',
        confidence: 99,
        status: 'PASS',
        viewSource: 'Front View',
        isMandatory: true,
      },
      {
        id: 'DEC-32',
        field: 'Net Quantity',
        hindiLabel: 'शुद्ध मात्रा',
        pcrRuleClause: 'Rule 6(1)(b) & Rule 9',
        extractedValue: '350 ml (Reduced from 400 ml)',
        standardRequirement: 'Standard package size & minimum letter height',
        confidence: 95,
        status: 'REVIEW',
        viewSource: 'Front View',
        isMandatory: true,
        inspectorNote: 'Volume reduced from 400 ml to 350 ml while packaging bottle height remained identical. Letter height reduced to 2.1mm.',
      },
      {
        id: 'DEC-33',
        field: 'Maximum Retail Price (MRP)',
        hindiLabel: 'अधिकतम खुदरा मूल्य',
        pcrRuleClause: 'Rule 6(1)(c)',
        extractedValue: '₹ 225.00 (Incl. of all taxes)',
        standardRequirement: 'Standard MRP statement',
        confidence: 96,
        status: 'PASS',
        viewSource: 'Back View',
        isMandatory: true,
      },
      {
        id: 'DEC-34',
        field: 'Unit Sale Price (USP)',
        hindiLabel: 'इकाई विक्रय मूल्य',
        pcrRuleClause: 'Rule 6(1)(e)',
        extractedValue: '₹ 0.64 / ml',
        standardRequirement: 'USP declaration adjacent to MRP',
        confidence: 94,
        status: 'PASS',
        viewSource: 'Back View',
        isMandatory: true,
      }
    ],
    fingerprintDiffs: [
      {
        fieldName: 'Net Quantity',
        previousValue: '400 ml',
        currentValue: '350 ml',
        changeType: 'SHRINKFLATION',
        severity: 'ALERT',
        ruleNote: '12.5% quantity reduction without proportionate retail packaging volume change. Requires verification of deceptive packaging under Section 36(1).',
      },
      {
        fieldName: 'Maximum Retail Price (MRP)',
        previousValue: '₹ 199.00',
        currentValue: '₹ 225.00',
        changeType: 'PRICE_CHANGE',
        severity: 'WARNING',
        ruleNote: 'Effective price increase of 29.3% per ml (from ₹0.50/ml to ₹0.64/ml). Declaration compliant with Rule 6, but historical shift flagged for market trend monitoring.',
      },
      {
        fieldName: 'Label Layout & Font Size',
        previousValue: 'Version 2.1 (Numeral height: 3.5mm)',
        currentValue: 'Version 3.0 (Numeral height: 2.1mm)',
        changeType: 'LABEL_REVISED',
        severity: 'WARNING',
        ruleNote: 'Font height reduced. Must be verified against Table I of Schedule II for surface area 120 cm².',
      },
      {
        fieldName: 'Manufacturer / Packer',
        previousValue: 'AyurVeda Naturals Pvt Ltd, Haridwar',
        currentValue: 'AyurVeda Naturals Pvt Ltd, Haridwar',
        changeType: 'NO_CHANGE',
        severity: 'INFO',
        ruleNote: 'Manufacturer registered address consistent across historical inspections.',
      }
    ]
  },

  'SAMPLE-SPECTRA': {
    id: 'INSP-2026-08495',
    date: '2026-09-05',
    timestamp: '15:25:18 IST',
    inspectorName: 'Rajesh Varma',
    inspectorId: 'GOI-LMO-DL-0482',
    inspectorRegion: 'North Zone — Delhi',
    productName: 'Himalayan Pure Pink Rock Salt',
    brand: 'Himalayan Pure',
    sku: 'HP-RS-1KG',
    barcode: '8909876543210',
    category: 'Spices & Condiments',
    overallStatus: 'REVIEW',
    overallScore: 78,
    sampleImages: {
      front: 'https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?auto=format&fit=crop&w=800&q=80',
      back: 'https://images.unsplash.com/photo-1506368249639-73a05d6f6488?auto=format&fit=crop&w=800&q=80',
      side: 'https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?auto=format&fit=crop&w=800&q=80',
      labelCloseUp: 'https://images.unsplash.com/photo-1534483509719-3feaee7c30da?auto=format&fit=crop&w=800&q=80',
    },
    declarations: [
      {
        id: 'DEC-41',
        field: 'Generic Name',
        hindiLabel: 'सामान्य नाम',
        pcrRuleClause: 'Rule 6(1)(a)',
        extractedValue: 'Iodised Himalayan Pink Rock Salt',
        standardRequirement: 'Generic declaration',
        confidence: 98,
        status: 'PASS',
        viewSource: 'Front View',
        isMandatory: true,
      },
      {
        id: 'DEC-42',
        field: 'Net Quantity',
        hindiLabel: 'शुद्ध मात्रा',
        pcrRuleClause: 'Rule 6(1)(b)',
        extractedValue: '1 kg',
        standardRequirement: 'Standard unit',
        confidence: 97,
        status: 'PASS',
        viewSource: 'Front View',
        isMandatory: true,
      },
      {
        id: 'DEC-43',
        field: 'Maximum Retail Price (MRP)',
        hindiLabel: 'अधिकतम खुदरा मूल्य',
        pcrRuleClause: 'Rule 6(1)(c)',
        extractedValue: '₹ 85.00 (Incl. of all taxes)',
        standardRequirement: 'MRP declaration',
        confidence: 95,
        status: 'PASS',
        viewSource: 'Back View',
        isMandatory: true,
      }
    ],
    spectraFindings: [
      {
        id: 'SPEC-01',
        zone: 'Batch Code & Hologram Security Ribbon',
        spectralBands: {
          rgbDescription: 'Standard monochrome dot-matrix printed text: "MFD 08/2026 BATCH 44A".',
          uvFluorescence: 'High-intensity yellow-green emission (520nm) detected under 365nm UV LED illumination, indicating non-specification optical brightening agents (OBA).',
          nirReflectance: 'Absence of expected carbon black absorption band at 850nm; indicative of dye-based organic ink rather than compliant pigment ink.',
        },
        anomalySignal: 'Multispectral Anomaly Signal Detected: Non-standard ink reflectance and substrate luminescence.',
        inspectorAdvisory: 'Physical security seal and ink formulation deviate from registered manufacturer master baseline. Recommended action: Submit sample to National Physical Laboratory (NPL) or Regional Reference Standards Laboratory (RRSL) for spectroscopic confirmation.',
        disclaimer: 'Notice: This module provides optical evidence signals only. Multispectral anomalies do not constitute legal proof of counterfeiting without formal laboratory chemical chromatography.',
      }
    ]
  }
};

export const RECENT_INSPECTIONS: InspectionRecord[] = [
  SAMPLE_PRODUCTS['SAMPLE-COMPLIANT'],
  SAMPLE_PRODUCTS['SAMPLE-LABELTRUTH'],
  SAMPLE_PRODUCTS['SAMPLE-ACTIVE-INSPECTION'],
  SAMPLE_PRODUCTS['SAMPLE-FINGERPRINT'],
  SAMPLE_PRODUCTS['SAMPLE-SPECTRA'],
  {
    id: 'INSP-2026-08490',
    date: '2026-09-04',
    timestamp: '16:45:10 IST',
    inspectorName: 'Rajesh Varma',
    inspectorId: 'GOI-LMO-DL-0482',
    inspectorRegion: 'North Zone — Delhi',
    productName: 'Patanjali Cow Ghee 1L',
    brand: 'Patanjali',
    sku: 'PAT-CG-1L',
    barcode: '8904109400234',
    category: 'Edible Oils & Fats',
    overallStatus: 'PASS',
    overallScore: 97,
    sampleImages: {
      front: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=800&q=80',
    },
    declarations: [],
    qrVerified: true,
  },
  {
    id: 'INSP-2026-08489',
    date: '2026-09-04',
    timestamp: '11:15:00 IST',
    inspectorName: 'Rajesh Varma',
    inspectorId: 'GOI-LMO-DL-0482',
    inspectorRegion: 'North Zone — Delhi',
    productName: 'Surf Excel Quick Wash 1kg',
    brand: 'Surf Excel',
    sku: 'HUL-SE-1KG',
    barcode: '8901030384721',
    category: 'Cleaning & Detergents',
    overallStatus: 'PASS',
    overallScore: 99,
    sampleImages: {
      front: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=800&q=80',
    },
    declarations: [],
    qrVerified: true,
  },
  {
    id: 'INSP-2026-08488',
    date: '2026-09-03',
    timestamp: '17:20:30 IST',
    inspectorName: 'Sunil Kumar (LMO South)',
    inspectorId: 'GOI-LMO-DL-0199',
    inspectorRegion: 'South Zone — Delhi',
    productName: 'SuperClean Dishwash Gel 750ml',
    brand: 'SuperClean',
    sku: 'SC-DG-750ML',
    barcode: '8907654321980',
    category: 'Cleaning & Detergents',
    overallStatus: 'FAIL',
    overallScore: 58,
    sampleImages: {
      front: 'https://images.unsplash.com/photo-1585751119414-ef2636f8aede?auto=format&fit=crop&w=800&q=80',
    },
    declarations: [],
    qrVerified: false,
  }
];

export const PORTAL_STATS = {
  totalInspections: 1248,
  compliant: 982,
  nonCompliant: 183,
  requiresReview: 83,
  complianceRate: 78.7,
  avgTurnaroundMinutes: 3.4,
  labelTruthInconsistencies: 42,
  multispectralAnomalies: 16,
};
