'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type LanguageCode = 'en' | 'hi' | 'ta' | 'te' | 'mr' | 'bn' | 'kn' | 'gu';

export interface LanguageOption {
  code: LanguageCode;
  label: string;
  nativeLabel: string;
  badge: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', label: 'English', nativeLabel: 'English', badge: 'EN' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी', badge: 'हि' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்', badge: 'த' },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు', badge: 'తె' },
  { code: 'mr', label: 'Marathi', nativeLabel: 'मराठी', badge: 'म' },
  { code: 'bn', label: 'Bengali', nativeLabel: 'বাংলা', badge: 'বা' },
  { code: 'kn', label: 'Kannada', nativeLabel: 'ಕನ್ನಡ', badge: 'ಕ' },
  { code: 'gu', label: 'Gujarati', nativeLabel: 'ગુજરાતી', badge: 'ગુ' },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Government Header & Branding
    dept_name_hi: 'उपभोक्ता मामले विभाग',
    dept_name_en: 'DEPARTMENT OF CONSUMER AFFAIRS',
    ministry_name: 'Ministry of Consumer Affairs, Food & Public Distribution',
    division_name: 'Legal Metrology Division',
    portal_title: 'PAKSHYA',
    portal_version: 'PORTAL V2.6',
    portal_subtitle: 'Legal Metrology Enforcement System',
    helpline_title: 'National Consumer Helpline',
    toll_free: '(Toll-Free)',
    
    // Navigation Tabs
    nav_dashboard: 'Dashboard',
    nav_new_inspection: 'New Inspection',
    nav_history: 'Inspection History',
    nav_products: 'Product Database',
    nav_rules: 'Acts & Rules',
    nav_font_size: 'Metrology Station',
    nav_analytics: 'Reports & Analytics',
    nav_help: 'Help & Resources',
    nav_more_tools: 'More Tools',
    nav_specialized_labs: 'Specialized Metrology Labs',
    nav_labeltruth: 'LabelTruth™ Cross-View',
    nav_labeltruth_desc: 'Rule 18(2) Dual MRP verification',
    nav_active_inspection: 'Active Inspection',
    nav_active_inspection_desc: 'Glare & curved label resolution',
    nav_fingerprint: 'Compliance Fingerprint',
    nav_fingerprint_desc: 'Shrinkflation & historic diff',
    nav_spectrashield: 'SpectraShield™ UV/NIR',
    nav_spectrashield_desc: 'Tamper & overlay forensics',
    nav_settings: 'Officer Settings',
    nav_settings_desc: 'Jurisdiction & device preferences',
    
    // Officer Dropdown & Notifications
    notifications: 'Directives & Metrology Alerts',
    mark_all_read: 'Mark All as Read',
    no_notifications: 'No unread notifications',
    field_authority: 'Field Authority:',
    posting_station: 'Posting Station:',
    todays_audits: "Today's Audits",
    inspections_count: 'Inspections',
    view_warrant: 'View Official Digital Warrant',
    sign_out: 'Sign Out of Field Duty',
    end_shift: 'End Shift',
    active_duty: 'Active Duty',
    session_active: 'Session: Active',
    nic_secured: 'Govt of India • NIC Secured',
    pcr_active: 'PCR 2011 Active',
    
    // Dashboard View
    dashboard_welcome: 'Legal Metrology Inspection & Enforcement Portal',
    dashboard_sub: 'Scan, verify and ensure statutory compliance of packaged commodities under the Legal Metrology (Packaged Commodities) Rules, 2011.',
    motto_title: 'NATIONAL ENFORCEMENT MOTTO',
    motto_text: '"Fair Measurement Builds a Fair Nation"',
    motto_dept: 'Department of Consumer Affairs • Govt. of India',
    live_sync: 'On Duty • Live Sync',
    stat_total_inspections: 'TOTAL INSPECTIONS',
    stat_total_sub: 'National Registry Count',
    stat_compliant: 'COMPLIANT PACKAGES',
    stat_compliant_sub: 'PCR 2011 Certified',
    stat_violations: 'NON-COMPLIANT / SEIZURE',
    stat_violations_sub: 'Notices Issued Sec 36(1)',
    stat_confidence: 'METROLOGY CONFIDENCE',
    stat_confidence_sub: 'OCR & ArUco Homography',
    
    // Workflow Steps
    step_1_title: '1. Scan Package',
    step_1_desc: 'Multi-view PDP capture',
    step_2_title: '2. AI Extraction',
    step_2_desc: '7 mandatory declarations',
    step_3_title: '3. Rule Audit',
    step_3_desc: 'Check PCR 2011 clauses',
    step_4_title: '4. Official Dossier',
    step_4_desc: 'Form LM-1 PDF export',
    
    // Upload Section
    upload_title: 'Upload Commodity Package Images',
    upload_sub: 'Upload multi-angle high-resolution photographs (Front PDP, Back Legal, Side, Macro Close-up) for statutory verification.',
    drag_drop_text: 'Drag & drop package photographs here',
    or: 'or',
    use_camera: 'Use Camera',
    browse_files: 'Browse Local Files',
    supports_types: 'Supports: JPEG, PNG, WEBP • Max 15 MB per evidence photograph',
    inspector_tip_label: 'Inspector Tip:',
    inspector_tip_text: 'Ensure adequate illumination and minimize surface glare. For Rule 9 numeral font verification, place the certified ArUco reference marker in the same plane.',
    recent_ledger: 'Recent Inspection Ledger',
    view_all: 'View All',
    
    // New Inspection Workspace
    step_upload: '1. Upload Evidence',
    step_extract: '2. AI Extraction',
    step_audit: '3. Verify & Audit',
    step_finalize: '4. Finalize & Sign',
    start_inspection: 'Start Inspection',
    analyzing: 'AI Inference in Progress...',
    running_ocr: 'Running OCR Engine...',
    matching_rules: 'Matching Statutory Rules...',
    product_detected: 'Product Detected',
    label_regions: 'Label Regions (PDP/Back)',
    ocr_completed: 'OCR Completed',
    dual_mrp_alert: 'Dual MRP Conflict Detected (Open LabelTruth)',
    resolve_ambiguity: 'Resolve Ambiguity (Active Inspection)',
    generate_report: 'Generate Official Report',
    reset: 'Reset',
    category: 'Category',
    barcode: 'Barcode',
    compliance_score: 'Compliance Score',
    col_declaration: 'Mandatory Declaration',
    col_rule: 'Statutory Rule Clause',
    col_detected: 'Detected Value',
    col_requirement: 'Rule Requirement',
    col_status: 'Status',
    col_evidence: 'Evidence',
    
    // Establishment Location & Geo-Tagging
    geotag_title: 'ESTABLISHMENT LOCATION & GEO-TAG',
    geotag_sub: 'Capture precise GPS coordinates of inspection establishment as required by Section 15 of Legal Metrology Act, 2009.',
    capture_location: 'Capture Current Location',
    capturing: 'Acquiring GPS Fix...',
    open_gmaps: 'Open in Google Maps',
    copy_coords: 'Copy Coordinates',
    copied: 'Copied!',
    latitude: 'Latitude',
    longitude: 'Longitude',
    gps_accuracy: 'GPS Accuracy (meters)',
    captured_at: 'Location Captured Date & Time',
    shop_address: 'Full Shop / Establishment Address',
    landmark: 'Landmark',
    district: 'District',
    state: 'State',
    pin_code: 'PIN Code',
    gmaps_link: 'Google Maps Link',
    establishment_name: 'Establishment / Shop Name',
    owner_name: 'Dealer / Proprietor / Representative Name',
    trade_license: 'Trade License / GSTIN / TIN',
    
    // Statutory Checklist
    checklist_title: 'OFFICIAL STATUTORY INSPECTION CHECKLIST',
    checklist_sub: 'Mandatory verification points under Legal Metrology Act, 2009 & Packaged Commodities Rules, 2011',
    rule_section: 'Rule / Section',
    statutory_requirement: 'Statutory Requirement',
    finding_status: 'Inspection Finding',
    
    // Consolidated Report & Seizure
    consolidated_title: 'OFFICIAL LEGAL METROLOGY INSPECTION & SEIZURE DOSSIER',
    form_number: 'Form LM-CONSOLIDATED/2026',
    view_unified: 'Consolidated Dossier (Single PDF)',
    view_interactive: 'Interactive Form Editor',
    print_pdf: 'Print Official Certificate (PDF)',
    export_json: 'Export Data (JSON)',
    create_seizure: 'Create Seizure Report',
    finalize_report: 'Finalize & Issue Notice',
    close: 'Close',
    sec_1_inspection_details: '1. INSPECTION & ESTABLISHMENT DETAILS',
    sec_2_geotag: '2. ESTABLISHMENT LOCATION & GEO-TAGGING EVIDENCE',
    sec_3_declarations: '3. STATUTORY DECLARATION AUDIT (PCR 2011)',
    sec_4_checklist: '4. STATUTORY VERIFICATION CHECKLIST (11 MANDATORY POINTS)',
    sec_5_photo_evidence: '5. PHOTOGRAPHIC GEO-EVIDENCE RECORD',
    sec_6_seizure_memo: '6. FORM OF SEIZURE MEMO & CUSTODY (LM ACT 2009 SEC. 15)',
    sec_7_signatures: '7. STATUTORY ATTESTATION & DIGITAL SIGNATURE',
    
    // Settings View
    settings_title: 'Settings',
    settings_sub: 'Manage your account, preferences, notifications and application settings.',
    app_preferences: 'Application Preferences',
    language_select: 'Language',
    date_format: 'Date Format',
    time_format: 'Time Format',
    default_view: 'Default View',
    items_per_page: 'Items per Page',
    profile_account: 'Profile & Account',
    edit_profile: 'Edit Profile',
    email: 'Email',
    phone: 'Phone',
    department: 'Department',
    jurisdiction: 'Jurisdiction',
    role: 'Role',
    
    // Status badges & common
    status_compliant: 'Compliant',
    status_violation: 'Violation',
    status_review: 'In Review',
    status_verified: 'Verified',
    status_pending: 'Pending',
    status_passed: 'PASS',
    status_failed: 'FAIL',
    save_draft: 'Save Draft',
    saved: 'Saved Successfully',
    select_language: 'Select Language',
  },
  
  hi: {
    // Government Header & Branding
    dept_name_hi: 'उपभोक्ता मामले विभाग',
    dept_name_en: 'DEPARTMENT OF CONSUMER AFFAIRS',
    ministry_name: 'उपभोक्ता मामले, खाद्य और सार्वजनिक वितरण मंत्रालय',
    division_name: 'विधिक मापविज्ञान प्रभाग',
    portal_title: 'पक्ष्य (PAKSHYA)',
    portal_version: 'पोर्टल V2.6',
    portal_subtitle: 'विधिक मापविज्ञान प्रवर्तन प्रणाली',
    helpline_title: 'राष्ट्रीय उपभोक्ता हेल्पलाइन',
    toll_free: '(टोल-फ्री)',
    
    // Navigation Tabs
    nav_dashboard: 'डैशबोर्ड',
    nav_new_inspection: 'नया निरीक्षण',
    nav_history: 'निरीक्षण इतिहास',
    nav_products: 'उत्पाद डेटाबेस',
    nav_rules: 'अधिनियम एवं नियम',
    nav_font_size: 'मापविज्ञान केंद्र',
    nav_analytics: 'रिपोर्ट व विश्लेषण',
    nav_help: 'सहायता एवं संसाधन',
    nav_more_tools: 'अन्य उपकरण',
    nav_specialized_labs: 'विशिष्ट मापविज्ञान प्रयोगशालाएं',
    nav_labeltruth: 'लेबलट्रुथ™ क्रॉस-व्यू',
    nav_labeltruth_desc: 'नियम 18(2) दोहरी एमआरपी सत्यापन',
    nav_active_inspection: 'सक्रिय निरीक्षण',
    nav_active_inspection_desc: 'चमक और घुमावदार लेबल समाधान',
    nav_fingerprint: 'अनुपालन फिंगरप्रिंट',
    nav_fingerprint_desc: 'श्रिंकफ्लेशन व ऐतिहासिक अंतर',
    nav_spectrashield: 'स्पेक्ट्राशील्ड™ UV/NIR',
    nav_spectrashield_desc: 'छेड़छाड़ व ओवरले फोरेंसिक',
    nav_settings: 'अधिकारी सेटिंग्स',
    nav_settings_desc: 'अधिकार क्षेत्र एवं उपकरण प्राथमिकताएं',
    
    // Officer Dropdown & Notifications
    notifications: 'निर्देश एवं मापविज्ञान अलर्ट',
    mark_all_read: 'सभी को पढ़ा हुआ मार्क करें',
    no_notifications: 'कोई अपठित अधिसूचना नहीं है',
    field_authority: 'क्षेत्र अधिकार:',
    posting_station: 'तैनाती केंद्र:',
    todays_audits: 'आज के ऑडिट',
    inspections_count: 'निरीक्षण',
    view_warrant: 'आधिकारिक डिजिटल वारंट देखें',
    sign_out: 'फील्ड ड्यूटी से साइन आउट करें',
    end_shift: 'शिफ्ट समाप्त करें',
    active_duty: 'सक्रिय ड्यूटी',
    session_active: 'सत्र: सक्रिय',
    nic_secured: 'भारत सरकार • एनआईसी सुरक्षित',
    pcr_active: 'पीसीआर 2011 सक्रिय',
    
    // Dashboard View
    dashboard_welcome: 'विधिक मापविज्ञान निरीक्षण एवं प्रवर्तन पोर्टल',
    dashboard_sub: 'विधिक मापविज्ञान (पैक की गई वस्तुएं) नियम, 2011 के तहत पैक की गई वस्तुओं का स्कैन, सत्यापन और वैधानिक अनुपालन सुनिश्चित करें।',
    motto_title: 'राष्ट्रीय प्रवर्तन आदर्श वाक्य',
    motto_text: '"सटीक माप, निष्पक्ष राष्ट्र का निर्माण"',
    motto_dept: 'उपभोक्ता मामले विभाग • भारत सरकार',
    live_sync: 'ड्यूटी पर • लाइव सिंक',
    stat_total_inspections: 'कुल निरीक्षण',
    stat_total_sub: 'राष्ट्रीय रजिस्ट्री संख्या',
    stat_compliant: 'अनुपालन योग्य पैकेज',
    stat_compliant_sub: 'पीसीआर 2011 प्रमाणित',
    stat_violations: 'गैर-अनुपालन / जब्ती',
    stat_violations_sub: 'धारा 36(1) के तहत नोटिस जारी',
    stat_confidence: 'मापविज्ञान सटीकता',
    stat_confidence_sub: 'ओसीआर एवं अरूको होमोग्राफी',
    
    // Workflow Steps
    step_1_title: '1. पैकेज स्कैन करें',
    step_1_desc: 'मल्टी-व्यू पीडीपी कैप्चर',
    step_2_title: '2. एआई निष्कर्षण',
    step_2_desc: '7 अनिवार्य घोषणाएं',
    step_3_title: '3. नियम ऑडिट',
    step_3_desc: 'पीसीआर 2011 खंडों की जांच',
    step_4_title: '4. आधिकारिक डोजियर',
    step_4_desc: 'फॉर्म एलएम-1 पीडीएफ निर्यात',
    
    // Upload Section
    upload_title: 'वस्तु पैकेज छवियां अपलोड करें',
    upload_sub: 'वैधानिक सत्यापन हेतु बहु-कोणीय उच्च-रिज़ॉल्यूशन तस्वीरें (सामने का पीडीपी, पीछे का कानूनी भाग, पार्श्व, मैक्रो क्लोज़-अप) अपलोड करें।',
    drag_drop_text: 'पैकेज की तस्वीरें यहां खींचें और छोड़ें',
    or: 'अथवा',
    use_camera: 'कैमरा उपयोग करें',
    browse_files: 'लोकल फाइलें चुनें',
    supports_types: 'समर्थित: JPEG, PNG, WEBP • प्रति साक्ष्य अधिकतम 15 MB',
    inspector_tip_label: 'निरीक्षक सुझाव:',
    inspector_tip_text: 'उचित प्रकाश व्यवस्था सुनिश्चित करें और सतह की चमक कम करें। नियम 9 अंक फ़ॉन्ट सत्यापन हेतु प्रमाणित अरूको मार्कर को एक ही तल पर रखें।',
    recent_ledger: 'हालिया निरीक्षण खाता',
    view_all: 'सभी देखें',
    
    // New Inspection Workspace
    step_upload: '1. साक्ष्य अपलोड',
    step_extract: '2. एआई निष्कर्षण',
    step_audit: '3. सत्यापन व ऑडिट',
    step_finalize: '4. अंतिम रूप एवं हस्ताक्षर',
    start_inspection: 'निरीक्षण शुरू करें',
    analyzing: 'एआई विश्लेषण जारी है...',
    running_ocr: 'ओसीआर इंजन चल रहा है...',
    matching_rules: 'वैधानिक नियमों का मिलान किया जा रहा है...',
    product_detected: 'उत्पाद पहचाना गया',
    label_regions: 'लेबल क्षेत्र (पीडीपी/पिछला)',
    ocr_completed: 'ओसीआर पूर्ण हुआ',
    dual_mrp_alert: 'दोहरी एमआरपी विसंगति पाई गई (लेबलट्रुथ खोलें)',
    resolve_ambiguity: 'संदेह निवारण (सक्रिय निरीक्षण)',
    generate_report: 'आधिकारिक रिपोर्ट तैयार करें',
    reset: 'रीसेट करें',
    category: 'श्रेणी',
    barcode: 'बारकोड',
    compliance_score: 'अनुपालन स्कोर',
    col_declaration: 'अनिवार्य घोषणा',
    col_rule: 'वैधानिक नियम खंड',
    col_detected: 'पहचाना गया मान',
    col_requirement: 'नियम आवश्यकता',
    col_status: 'स्थिति',
    col_evidence: 'साक्ष्य',
    
    // Establishment Location & Geo-Tagging
    geotag_title: 'प्रतिष्ठान स्थान एवं जियो-टैग',
    geotag_sub: 'विधिक मापविज्ञान अधिनियम, 2009 की धारा 15 के अनुसार निरीक्षण प्रतिष्ठान के सटीक जीपीएस निर्देशांक कैप्चर करें।',
    capture_location: 'वर्तमान स्थान कैप्चर करें',
    capturing: 'जीपीएस लोकेशन प्राप्त हो रहा है...',
    open_gmaps: 'गूगल मैप्स में खोलें',
    copy_coords: 'निर्देशांक कॉपी करें',
    copied: 'कॉपी किया गया!',
    latitude: 'अक्षांश (Latitude)',
    longitude: 'देशांतर (Longitude)',
    gps_accuracy: 'जीपीएस सटीकता (मीटर)',
    captured_at: 'स्थान कैप्चर तिथि एवं समय',
    shop_address: 'दुकान / प्रतिष्ठान का पूरा पता',
    landmark: 'लैंडमार्क / सीमा चिह्न',
    district: 'जिला',
    state: 'राज्य',
    pin_code: 'पिन कोड',
    gmaps_link: 'गूगल मैप्स लिंक',
    establishment_name: 'प्रतिष्ठान / दुकान का नाम',
    owner_name: 'विक्रेता / स्वामी / प्रतिनिधि का नाम',
    trade_license: 'व्यापार लाइसेंस / जीएसटीआईएन',
    
    // Statutory Checklist
    checklist_title: 'आधिकारिक वैधानिक निरीक्षण चेकलिस्ट',
    checklist_sub: 'विधिक मापविज्ञान अधिनियम, 2009 और पैक की गई वस्तुएं नियम, 2011 के तहत अनिवार्य सत्यापन बिंदु',
    rule_section: 'नियम / धारा',
    statutory_requirement: 'वैधानिक आवश्यकता',
    finding_status: 'निरीक्षण परिणाम',
    
    // Consolidated Report & Seizure
    consolidated_title: 'आधिकारिक विधिक मापविज्ञान निरीक्षण एवं जब्ती डोजियर',
    form_number: 'फॉर्म एलएम-समेकित/2026',
    view_unified: 'समेकित डोजियर (एकल पीडीएफ)',
    view_interactive: 'संवादात्मक फॉर्म संपादक',
    print_pdf: 'आधिकारिक प्रमाण पत्र प्रिंट करें (PDF)',
    export_json: 'डेटा निर्यात करें (JSON)',
    create_seizure: 'जब्ती रिपोर्ट बनाएं',
    finalize_report: 'अंतिम रूप दें एवं नोटिस जारी करें',
    close: 'बंद करें',
    sec_1_inspection_details: '1. निरीक्षण एवं प्रतिष्ठान विवरण',
    sec_2_geotag: '2. प्रतिष्ठान स्थान एवं जियो-टैगिंग साक्ष्य',
    sec_3_declarations: '3. वैधानिक घोषणा ऑडिट (पीसीआर 2011)',
    sec_4_checklist: '4. वैधानिक सत्यापन चेकलिस्ट (11 अनिवार्य बिंदु)',
    sec_5_photo_evidence: '5. फोटोग्राफिक जियो-साक्ष्य रिकॉर्ड',
    sec_6_seizure_memo: '6. जब्ती ज्ञापन एवं अभिरक्षा प्रपत्र (एलएम अधिनियम धारा 15)',
    sec_7_signatures: '7. वैधानिक प्रमाणीकरण एवं डिजिटल हस्ताक्षर',
    
    // Settings View
    settings_title: 'सेटिंग्स',
    settings_sub: 'अपना खाता, प्राथमिकताएं, सूचनाएं और एप्लिकेशन सेटिंग्स प्रबंधित करें।',
    app_preferences: 'एप्लिकेशन प्राथमिकताएं',
    language_select: 'भाषा (Language)',
    date_format: 'दिनांक प्रारूप',
    time_format: 'समय प्रारूप',
    default_view: 'डिफ़ॉल्ट दृश्य',
    items_per_page: 'प्रति पृष्ठ आइटम',
    profile_account: 'प्रोफ़ाइल एवं खाता',
    edit_profile: 'प्रोफ़ाइल संपादित करें',
    email: 'ईमेल',
    phone: 'फ़ोन',
    department: 'विभाग',
    jurisdiction: 'अधिकार क्षेत्र',
    role: 'भूमिका',
    
    // Status badges & common
    status_compliant: 'अनुपालन योग्य',
    status_violation: 'उल्लंघन',
    status_review: 'समीक्षाधीन',
    status_verified: 'सत्यापित',
    status_pending: 'लंबित',
    status_passed: 'उत्तीर्ण',
    status_failed: 'विफल',
    save_draft: 'ड्राफ्ट सहेजें',
    saved: 'सफलतापूर्वक सहेजा गया',
    select_language: 'भाषा चुनें',
  },

  ta: {
    // Government Header & Branding
    dept_name_hi: 'उपभोक्ता मामले विभाग',
    dept_name_en: 'DEPARTMENT OF CONSUMER AFFAIRS',
    ministry_name: 'நுகர்வோர் விவகாரங்கள், உணவு மற்றும் பொது விநியோக அமைச்சகம்',
    division_name: 'சட்ட அளவியல் பிரிவு (Legal Metrology)',
    portal_title: 'பக்ஷ்யா (PAKSHYA)',
    portal_version: 'போர்ட்டல் V2.6',
    portal_subtitle: 'சட்ட அளவியல் அமலாக்க அமைப்பு',
    helpline_title: 'தேசிய நுகர்வோர் உதவி எண்',
    toll_free: '(கட்டணமில்லா எண்)',
    
    // Navigation Tabs
    nav_dashboard: 'முகப்பு',
    nav_new_inspection: 'புதிய ஆய்வு',
    nav_history: 'ஆய்வு வரலாறு',
    nav_products: 'தயாரிப்பு தரவுத்தளம்',
    nav_rules: 'சட்டங்கள் & விதிகள்',
    nav_font_size: 'அளவியல் நிலையம்',
    nav_analytics: 'அறிக்கைகள் & பகுப்பாய்வு',
    nav_help: 'உதவி & வளங்கள்',
    nav_more_tools: 'கூடுதல் கருவிகள்',
    nav_specialized_labs: 'சிறப்பு அளவியல் ஆய்வகங்கள்',
    nav_labeltruth: 'லேபல்ட்ரூத்™ பார்வை',
    nav_labeltruth_desc: 'விதி 18(2) இரட்டை MRP சரிபார்ப்பு',
    nav_active_inspection: 'நேரடி ஆய்வு',
    nav_active_inspection_desc: 'ஒளிரும் & வளைந்த லேபிள் தீர்வு',
    nav_fingerprint: 'இணக்க கைரேகை',
    nav_fingerprint_desc: 'சுருக்கவீக்கம் & வரலாற்று வேறுபாடு',
    nav_spectrashield: 'ஸ்பெக்ட்ராஷீல்ட்™ UV/NIR',
    nav_spectrashield_desc: 'சிதைவு தடயவியல் ஆய்வு',
    nav_settings: 'அதிகாரி அமைப்புகள்',
    nav_settings_desc: 'அதிகார வரம்பு & விருப்பத்தேர்வுகள்',
    
    // Officer Dropdown & Notifications
    notifications: 'உத்தரவுகள் & அளவியல் எச்சரிக்கைகள்',
    mark_all_read: 'அனைத்தையும் படித்ததாகக் குறிக்கவும்',
    no_notifications: 'புதிய அறிவிப்புகள் இல்லை',
    field_authority: 'கள அதிகாரம்:',
    posting_station: 'பணி நிலையம்:',
    todays_audits: 'இன்றைய தணிக்கைகள்',
    inspections_count: 'ஆய்வுகள்',
    view_warrant: 'அதிகாரப்பூர்வ டிஜிட்டல் ஆணை காண்க',
    sign_out: 'களப் பணியிலிருந்து வெளியேறு',
    end_shift: 'ஷிப்ட் முடிக்க',
    active_duty: 'செயலில் உள்ள பணி',
    session_active: 'அமர்வு: செயலில் உள்ளது',
    nic_secured: 'இந்திய அரசு • NIC பாதுகாப்பு',
    pcr_active: 'PCR 2011 அமலில் உள்ளது',
    
    // Dashboard View
    dashboard_welcome: 'சட்ட அளவியல் ஆய்வு மற்றும் அமலாக்க தளம்',
    dashboard_sub: 'சட்ட அளவியல் (பொதி செய்யப்பட்ட பொருட்கள்) விதிகள், 2011 இன் கீழ் சட்டப்பூர்வ இணக்கத்தை சரிபார்க்கவும்.',
    motto_title: 'தேசிய அமலாக்க முழக்கம்',
    motto_text: '"நியாயமான அளவீடு, நியாயமான தேசத்தை உருவாக்குகிறது"',
    motto_dept: 'நுகர்வோர் விவகாரங்கள் துறை • இந்திய அரசு',
    live_sync: 'பணியில் • நேரடி ஒத்திசைவு',
    stat_total_inspections: 'மொத்த ஆய்வுகள்',
    stat_total_sub: 'தேசிய பதிவு எண்ணிக்கை',
    stat_compliant: 'விதிமுறைகளுக்கு உட்பட்டவை',
    stat_compliant_sub: 'PCR 2011 சான்றளிக்கப்பட்டது',
    stat_violations: 'விதிமீறல் / பறிமுதல்',
    stat_violations_sub: 'பிரிவு 36(1) இன் கீழ் அறிவிப்பு',
    stat_confidence: 'அளவியல் துல்லியம்',
    stat_confidence_sub: 'OCR மற்றும் ArUco முறை',
    
    // Workflow Steps
    step_1_title: '1. பொதியை ஸ்கேன் செய்',
    step_1_desc: 'பல்வேறு கோணங்களில் படம் எடுத்தல்',
    step_2_title: '2. AI பிரித்தெடுத்தல்',
    step_2_desc: '7 கட்டாய அறிவிப்புகள்',
    step_3_title: '3. விதி தணிக்கை',
    step_3_desc: 'PCR 2011 பிரிவுகளை சரிபார்த்தல்',
    step_4_title: '4. அதிகாரப்பூர்வ ஆவணம்',
    step_4_desc: 'படிவம் LM-1 PDF ஏற்றுமதி',
    
    // Upload Section
    upload_title: 'பொருளின் புகைப்படங்களை பதிவேற்றவும்',
    upload_sub: 'சட்டப்பூர்வ சரிபார்ப்புக்கு தெளிவான புகைப்படங்களை (முன்பக்கம், பின்பக்க லேபிள், பக்கவாட்டு) பதிவேற்றவும்.',
    drag_drop_text: 'புகைப்படங்களை இங்கே இழுத்து விடவும்',
    or: 'அல்லது',
    use_camera: 'கேமரா பயன்படுத்தவும்',
    browse_files: 'கோப்புகளைத் தேர்ந்தெடுக்கவும்',
    supports_types: 'ஆதரிப்பவை: JPEG, PNG, WEBP • அதிகபட்சம் 15 MB',
    inspector_tip_label: 'ஆய்வாளர் குறிப்பு:',
    inspector_tip_text: 'சரியான வெளிச்சம் இருப்பதை உறுதி செய்யவும். எழுத்துரு உயரத்தை அளவிட ArUco குறியீட்டை ஒரே தளத்தில் வைக்கவும்.',
    recent_ledger: 'சமீபத்திய ஆய்வு பதிவேடு',
    view_all: 'அனைத்தும் காண்க',
    
    // New Inspection Workspace
    step_upload: '1. சான்றுகள் பதிவேற்றம்',
    step_extract: '2. AI தரவு எடுத்தல்',
    step_audit: '3. சரிபார்ப்பு & தணிக்கை',
    step_finalize: '4. இறுதிசெய்து கையொப்பமிடு',
    start_inspection: 'ஆய்வைத் தொடங்கு',
    analyzing: 'AI ஆய்வு நடைபெறுகிறது...',
    running_ocr: 'OCR உரை அடையாளம் காணப்படுகிறது...',
    matching_rules: 'சட்ட விதிகள் ஒப்பிடப்படுகின்றன...',
    product_detected: 'பொருள் கண்டறியப்பட்டது',
    label_regions: 'லேபிள் பகுதிகள்',
    ocr_completed: 'OCR முடிந்தது',
    dual_mrp_alert: 'இரட்டை MRP முரண்பாடு உள்ளது (லேபல்ட்ரூத் திறக்கவும்)',
    resolve_ambiguity: 'தெளிவுபடுத்தல் (நேரடி ஆய்வு)',
    generate_report: 'அறிக்கை உருவாக்கவும்',
    reset: 'மீட்டமைக்க',
    category: 'வகை',
    barcode: 'பார்கோடு',
    compliance_score: 'இணக்க மதிப்பீடு',
    col_declaration: 'கட்டாய அறிவிப்பு',
    col_rule: 'சட்ட விதி பிரிவு',
    col_detected: 'கண்டறியப்பட்ட மதிப்பு',
    col_requirement: 'விதி தேவை',
    col_status: 'நிலை',
    col_evidence: 'சான்று',
    
    // Establishment Location & Geo-Tagging
    geotag_title: 'நிறுவனத்தின் இருப்பிடம் & ஜியோ-டேக்',
    geotag_sub: 'சட்ட அளவியல் சட்டம் 2009 பிரிவு 15 இன் படி ஆய்வு நிறுவனத்தின் துல்லியமான GPS அமைப்பை பதிவு செய்யவும்.',
    capture_location: 'தற்போதைய இருப்பிடத்தைப் பெறுக',
    capturing: 'GPS பெறப்படுகிறது...',
    open_gmaps: 'கூகுள் வரைபடத்தில் திற',
    copy_coords: 'ஆயத்தொலைவுகளை நகலெடு',
    copied: 'நகலெடுக்கப்பட்டது!',
    latitude: 'அட்சரேகை (Latitude)',
    longitude: 'தீர்க்கரேகை (Longitude)',
    gps_accuracy: 'GPS துல்லியம் (மீட்டர்கள்)',
    captured_at: 'பதிவு செய்யப்பட்ட தேதி & நேரம்',
    shop_address: 'கடை / நிறுவனத்தின் முழு முகவரி',
    landmark: 'அடையாளக் குறி (Landmark)',
    district: 'மாவட்டம்',
    state: 'மாநிலம்',
    pin_code: 'அஞ்சல் குறியீடு (PIN)',
    gmaps_link: 'கூகுள் வரைபட இணைப்பு',
    establishment_name: 'நிறுவனம் / கடையின் பெயர்',
    owner_name: 'உரிமையாளர் / விற்பனையாளர் பெயர்',
    trade_license: 'வணிக உரிமம் / GSTIN',
    
    // Statutory Checklist
    checklist_title: 'அதிகாரப்பூர்வ சட்டப்பூர்வ சரிபார்ப்புப் பட்டியல்',
    checklist_sub: 'சட்ட அளவியல் சட்டம் 2009 மற்றும் PCR 2011 இன் கீழ் கட்டாய சரிபார்ப்பு புள்ளிகள்',
    rule_section: 'விதி / பிரிவு',
    statutory_requirement: 'சட்டப்பூர்வ தேவை',
    finding_status: 'ஆய்வு முடிவு',
    
    // Consolidated Report & Seizure
    consolidated_title: 'அதிகாரப்பூர்வ சட்ட அளவியல் ஆய்வு மற்றும் பறிமுதல் ஆவணம்',
    form_number: 'படிவம் LM-ஒருங்கிணைந்த/2026',
    view_unified: 'ஒருங்கிணைந்த ஆவணம் (ஒற்றை PDF)',
    view_interactive: 'படிவ திருத்தி',
    print_pdf: 'சான்றிதழை அச்சிடுக (PDF)',
    export_json: 'தரவு ஏற்றுமதி (JSON)',
    create_seizure: 'பறிமுதல் அறிக்கை உருவாக்கு',
    finalize_report: 'இறுதி செய்து நோட்டீஸ் வழங்குக',
    close: 'மூடுக',
    sec_1_inspection_details: '1. ஆய்வு மற்றும் நிறுவன விவரங்கள்',
    sec_2_geotag: '2. நிறுவன இருப்பிடம் & புவிசார் சான்று',
    sec_3_declarations: '3. சட்டப்பூர்வ அறிவிப்பு தணிக்கை (PCR 2011)',
    sec_4_checklist: '4. கட்டாய சரிபார்ப்பு பட்டியல் (11 புள்ளிகள்)',
    sec_5_photo_evidence: '5. புகைப்பட புவி-சான்று பதிவு',
    sec_6_seizure_memo: '6. பறிமுதல் மெமோ மற்றும் காவல் படிவம் (பிரிவு 15)',
    sec_7_signatures: '7. சட்டப்பூர்வ சான்றளிப்பு & டிஜிட்டல் கையொப்பம்',
    
    // Settings View
    settings_title: 'அமைப்புகள்',
    settings_sub: 'உங்கள் கணக்கு, விருப்பத்தேர்வுகள் மற்றும் பயன்பாட்டு அமைப்புகளை நிர்வகிக்கவும்.',
    app_preferences: 'பயன்பாட்டு விருப்பத்தேர்வுகள்',
    language_select: 'மொழி (Language)',
    date_format: 'தேதி வடிவம்',
    time_format: 'நேர வடிவம்',
    default_view: 'இயல்புநிலை பார்வை',
    items_per_page: 'ஒரு பக்கத்திற்கான உருப்படிகள்',
    profile_account: 'சுயவிவரம் & கணக்கு',
    edit_profile: 'சுயவிவரம் திருத்து',
    email: 'மின்னஞ்சல்',
    phone: 'தொலைபேசி',
    department: 'துறை',
    jurisdiction: 'அதிகார வரம்பு',
    role: 'பணி நிலை',
    
    // Status badges & common
    status_compliant: 'விதிமுறைகளுக்கு உட்பட்டது',
    status_violation: 'விதிமீறல்',
    status_review: 'மறுஆய்வில்',
    status_verified: 'சரிபார்க்கப்பட்டது',
    status_pending: 'நிலுவையில்',
    status_passed: 'வெற்றி',
    status_failed: 'தோல்வி',
    save_draft: 'வரைவை சேமிக்கவும்',
    saved: 'வெற்றிகரமாக சேமிக்கப்பட்டது',
    select_language: 'மொழியைத் தேர்ந்தெடுக்கவும்',
  },

  te: {
    // Government Header & Telugu
    dept_name_hi: 'उपभोक्ता मामले विभाग',
    dept_name_en: 'DEPARTMENT OF CONSUMER AFFAIRS',
    ministry_name: 'వినియోగదారుల వ్యవహారాలు, ఆహార & ప్రజా పంపిణీ మంత్రిత్వ శాఖ',
    division_name: 'లీగల్ మెట్రాలజీ విభాగం (Legal Metrology)',
    portal_title: 'పక్ష్య (PAKSHYA)',
    portal_version: 'పోర్టల్ V2.6',
    portal_subtitle: 'లీగల్ మెట్రాలజీ అమలు వ్యవస్థ',
    helpline_title: 'జాతీయ వినియోగదారుల హెల్ప్‌లైన్',
    toll_free: '(టోల్-ఫ్రీ)',
    nav_dashboard: 'డాష్‌బోర్డ్',
    nav_new_inspection: 'కొత్త తనిఖీ',
    nav_history: 'తనిఖీ చరిత్ర',
    nav_products: 'ఉత్పత్తి డేటాబేస్',
    nav_rules: 'చట్టాలు & నిబంధనలు',
    nav_font_size: 'మెట్రాలజీ కేంద్రం',
    nav_analytics: 'నివేదికలు & విశ్లేషణ',
    nav_help: 'సహాయం & వనరులు',
    nav_more_tools: 'మరిన్ని సాధనాలు',
    nav_specialized_labs: 'ప్రత్యేక మెట్రాలజీ ల్యాబ్‌లు',
    nav_labeltruth: 'లేబుల్‌ట్రూత్™ క్రాస్-వ్యూ',
    nav_labeltruth_desc: 'నియమం 18(2) ద్వంద్వ MRP ధృవీకరణ',
    nav_active_inspection: 'సక్రియ తనిఖీ',
    nav_active_inspection_desc: 'స్పష్టత లేని లేబుల్ పరిష్కారం',
    nav_fingerprint: 'సమ్మతి వేలిముద్ర',
    nav_fingerprint_desc: 'ష్రింక్‌ఫ్లేషన్ తేడాల గుర్తింపు',
    nav_spectrashield: 'స్పెక్ట్రాషీల్డ్™ UV/NIR',
    nav_spectrashield_desc: 'టాంపరింగ్ ఫోరెన్సిక్స్',
    nav_settings: 'అధికారి సెట్టింగ్‌లు',
    nav_settings_desc: 'పరిధి & పరికర ప్రాధాన్యతలు',
    dashboard_welcome: 'లీగల్ మెట్రాలజీ తనిఖీ & ఎన్‌ఫోర్స్‌మెంట్ పోర్టల్',
    dashboard_sub: 'లీగల్ మెట్రాలజీ నియమాలు 2011 కింద ప్యాక్ చేసిన వస్తువుల తనిఖీ మరియు చట్టబద్ధమైన సమ్మతిని నిర్ధారించండి.',
    motto_title: 'జాతీయ అమలు నినాదం',
    motto_text: '"సరైన కొలత, సమగ్ర దేశాన్ని నిర్మిస్తుంది"',
    motto_dept: 'వినియోగదారుల వ్యవహారాల శాఖ • భారత ప్రభుత్వం',
    stat_total_inspections: 'మొత్తం తనిఖీలు',
    stat_compliant: 'నిబంధనలకు లోబడినవి',
    stat_violations: 'ఉల్లంఘన / స్వాధీనం',
    stat_confidence: 'మెట్రాలజీ ఖచ్చితత్వం',
    capture_location: 'ప్రస్తుత స్థానాన్ని రికార్డ్ చేయండి',
    capturing: 'GPS పొందుతోంది...',
    open_gmaps: 'గూగుల్ మ్యాప్స్‌లో చూడండి',
    copy_coords: 'కోఆర్డినేట్‌లను కాపీ చేయండి',
    copied: 'కాపీ చేయబడింది!',
    geotag_title: 'వ్యాపార సంస్థ స్థానం & జియో-ట్యాగ్',
    shop_address: 'దుకాణం / సంస్థ పూర్తి చిరునామా',
    district: 'జిల్లా',
    state: 'రాష్ట్రం',
    pin_code: 'పిన్ కోడ్',
    generate_report: 'అధికారిక నివేదికను రూపొందించండి',
    reset: 'రీసెట్ చేయండి',
    view_unified: 'ఏకీకృత నివేదిక (సింగిల్ PDF)',
    print_pdf: 'సర్టిఫికేట్ ప్రింట్ చేయండి (PDF)',
    export_json: 'డేటా ఎగుమతి (JSON)',
    settings_title: 'సెట్టింగ్‌లు',
    language_select: 'భాష (Language)',
    status_compliant: 'అనుకూలం',
    status_violation: 'ఉల్లంఘన',
    status_review: 'సమీక్షలో ఉంది',
    select_language: 'భాషను ఎంచుకోండి',
  },

  mr: {
    // Marathi
    dept_name_hi: 'उपभोक्ता मामले विभाग',
    dept_name_en: 'DEPARTMENT OF CONSUMER AFFAIRS',
    ministry_name: 'ग्राहक व्यवहार, अन्न आणि सार्वजनिक वितरण मंत्रालय',
    division_name: 'वैधानिक मापनशास्त्र विभाग (Legal Metrology)',
    portal_title: 'पक्ष्य (PAKSHYA)',
    portal_version: 'पोर्टल V2.6',
    portal_subtitle: 'वैधानिक मापनशास्त्र अंमलबजावणी प्रणाली',
    helpline_title: 'राष्ट्रीय ग्राहक हेल्पलाइन',
    toll_free: '(टोल-फ्री)',
    nav_dashboard: 'डॅशबोर्ड',
    nav_new_inspection: 'नवीन तपासणी',
    nav_history: 'तपासणी इतिहास',
    nav_products: 'उत्पादन डेटाबेस',
    nav_rules: 'कायदे व नियम',
    nav_font_size: 'मापनशास्त्र केंद्र',
    nav_analytics: 'अहवाल व विश्लेषण',
    nav_help: 'मदत व संसाधने',
    nav_more_tools: 'इतर साधने',
    nav_specialized_labs: 'विशेष मापनशास्त्र प्रयोगशाळा',
    nav_labeltruth: 'लेबलट्रुथ™ क्रॉस-व्ह्यू',
    nav_labeltruth_desc: 'नियम 18(2) दुहेरी एमआरपी पडताळणी',
    nav_active_inspection: 'थेट तपासणी',
    nav_active_inspection_desc: 'अस्पष्ट लेबल निराकरण',
    nav_fingerprint: 'अनुपालन फिंगरप्रिंट',
    nav_fingerprint_desc: 'श्रिंकफ्लेशन व फरक शोध',
    nav_spectrashield: 'स्पेक्ट्राशील्ड™ UV/NIR',
    nav_spectrashield_desc: 'छेडछाड फॉरेन्सिक्स',
    nav_settings: 'अधिकारी सेटिंग्ज',
    nav_settings_desc: 'अधिकारक्षेत्र व प्राधान्ये',
    dashboard_welcome: 'वैधानिक मापनशास्त्र तपासणी व अंमलबजावणी पोर्टल',
    dashboard_sub: 'पॅक केलेल्या वस्तू नियम, 2011 अंतर्गत वस्तूंची कायदेशीर तपासणी आणि पडताळणी करा.',
    motto_title: 'राष्ट्रीय अंमलबजावणी ब्रीदवाक्य',
    motto_text: '"अचूक मापन, निष्पक्ष राष्ट्राची उभारणी"',
    motto_dept: 'ग्राहक व्यवहार विभाग • भारत सरकार',
    stat_total_inspections: 'एकूण तपासण्या',
    stat_compliant: 'नियमानुसार पॅकेजेस',
    stat_violations: 'उल्लंघन / जप्ती',
    stat_confidence: 'मापनशास्त्र अचूकता',
    capture_location: 'वर्तमान स्थान मिळवा',
    capturing: 'GPS शोधत आहे...',
    open_gmaps: 'गुगल मॅप्सवर उघडा',
    copy_coords: 'निर्देशांक कॉपी करा',
    copied: 'कॉपी केले!',
    geotag_title: 'प्रतिष्ठान स्थान व जिओ-टॅग',
    shop_address: 'दुकान / आस्थापनेचा पूर्ण पत्ता',
    district: 'जिल्हा',
    state: 'राज्य',
    pin_code: 'पिन कोड',
    generate_report: 'अधिकृत अहवाल तयार करा',
    reset: 'रीसेट करा',
    view_unified: 'एकत्रित अहवाल (एकल PDF)',
    print_pdf: 'प्रमाणपत्र मुद्रित करा (PDF)',
    export_json: 'डेटा निर्यात (JSON)',
    settings_title: 'सेटिंग्ज',
    language_select: 'भाषा (Language)',
    status_compliant: 'सुसंगत',
    status_violation: 'उल्लंघन',
    status_review: 'पुनरावलोकनात',
    select_language: 'भाषा निवडा',
  },

  bn: {
    // Bengali
    dept_name_hi: 'उपभोक्ता मामले विभाग',
    dept_name_en: 'DEPARTMENT OF CONSUMER AFFAIRS',
    ministry_name: 'ভোক্তা বিষয়ক, খাদ্য ও গণবণ্টন মন্ত্রক',
    division_name: 'আইনগত পরিমাপবিদ্যা বিভাগ (Legal Metrology)',
    portal_title: 'পক্ষ্য (PAKSHYA)',
    portal_version: 'পোর্টাল V2.6',
    portal_subtitle: 'আইনগত পরিমাপ প্রয়োগ ব্যবস্থা',
    helpline_title: 'জাতীয় ভোক্তা হেল্পলাইন',
    toll_free: '(টোল-ফ্রি)',
    nav_dashboard: 'ড্যাশবোর্ড',
    nav_new_inspection: 'নতুন পরিদর্শন',
    nav_history: 'পরিদর্শন ইতিহাস',
    nav_products: 'পণ্য ডাটাবেস',
    nav_rules: 'আইন ও বিধিমালা',
    nav_font_size: 'পরিমাপ স্টেশন',
    nav_analytics: 'রিপোর্ট ও বিশ্লেষণ',
    nav_help: 'সহায়তা ও সংস্থান',
    nav_more_tools: 'আরও সরঞ্জাম',
    nav_specialized_labs: 'বিশেষ পরিমাপ ল্যাব',
    nav_labeltruth: 'লেবেলট্রুথ™ ক্রস-ভিউ',
    nav_labeltruth_desc: 'বিধি ১৮(২) দ্বৈত এমআরপি যাচাই',
    nav_active_inspection: 'সক্রিয় পরিদর্শন',
    nav_active_inspection_desc: 'অস্পষ্ট লেবেল সমাধান',
    nav_fingerprint: 'সম্মতি আঙুলের ছাপ',
    nav_fingerprint_desc: 'সংকোচন ও ঐতিহাসিক পার্থক্য',
    nav_spectrashield: 'স্পেক্ট্রাশিল্ড™ UV/NIR',
    nav_spectrashield_desc: 'ফরেনসিক বিশ্লেষণ',
    nav_settings: 'অফিসার সেটিংস',
    nav_settings_desc: 'এখতিয়ার ও পছন্দসমূহ',
    dashboard_welcome: 'আইনি পরিমাপ পরিদর্শন ও প্রয়োগ পোর্টাল',
    dashboard_sub: 'প্যাকেজজাত পণ্য বিধিমালা, ২০১১-এর অধীনে পণ্যের আইনি সম্মতি নিশ্চিত করুন।',
    motto_title: 'জাতীয় প্রয়োগের মূলমন্ত্র',
    motto_text: '"সঠিক পরিমাপ, ন্যায্য জাতি গঠন করে"',
    motto_dept: 'ভোক্তা বিষয়ক বিভাগ • ভারত সরকার',
    stat_total_inspections: 'মোট পরিদর্শন',
    stat_compliant: 'বিধি মেনে চলা পণ্য',
    stat_violations: 'লঙ্ঘন / বাজেয়াপ্ত',
    stat_confidence: 'পরিমাপ যথার্থতা',
    capture_location: 'বর্তমান অবস্থান ক্যাপচার করুন',
    capturing: 'GPS পাওয়া যাচ্ছে...',
    open_gmaps: 'গুগল ম্যাপে খুলুন',
    copy_coords: 'স্থানাঙ্ক কপি করুন',
    copied: 'কপি করা হয়েছে!',
    geotag_title: 'প্রতিষ্ঠানের অবস্থান ও জিও-ট্যাগ',
    shop_address: 'দোকান / প্রতিষ্ঠানের সম্পূর্ণ ঠিকানা',
    district: 'জেলা',
    state: 'রাজ্য',
    pin_code: 'পিন কোড',
    generate_report: 'অফিসিয়াল রিপোর্ট তৈরি করুন',
    reset: 'রিসেট করুন',
    view_unified: 'একীভূত ডসিয়ার (একক PDF)',
    print_pdf: 'সার্টিফিকেট প্রিন্ট করুন (PDF)',
    export_json: 'ডেটা এক্সপোর্ট (JSON)',
    settings_title: 'সেটিংস',
    language_select: 'ভাষা (Language)',
    status_compliant: 'সম্মত',
    status_violation: 'লঙ্ঘন',
    status_review: 'পর্যালোচনাধীন',
    select_language: 'ভাষা নির্বাচন করুন',
  },

  kn: {
    // Kannada
    dept_name_hi: 'उपभोक्ता मामले विभाग',
    dept_name_en: 'DEPARTMENT OF CONSUMER AFFAIRS',
    ministry_name: 'ಗ್ರಾಹಕ ವ್ಯವಹಾರಗಳು, ಆಹಾರ ಮತ್ತು ಸಾರ್ವಜನಿಕ ವಿತರಣಾ ಸಚಿವಾಲಯ',
    division_name: 'ಕಾನೂನು ಮಾಪನಶಾಸ್ತ್ರ ವಿಭಾಗ (Legal Metrology)',
    portal_title: 'ಪಕ್ಷ್ಯ (PAKSHYA)',
    portal_version: 'ಪೋರ್ಟಲ್ V2.6',
    portal_subtitle: 'ಕಾನೂನು ಮಾಪನಶಾಸ್ತ್ರ ಜಾರಿ ವ್ಯವಸ್ಥೆ',
    helpline_title: 'ರಾಷ್ಟ್ರೀಯ ಗ್ರಾಹಕ ಸಹಾಯವಾಣಿ',
    toll_free: '(ಟೋಲ್-ಫ್ರೀ)',
    nav_dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    nav_new_inspection: 'ಹೊಸ ತಪಾಸಣೆ',
    nav_history: 'ತಪಾಸಣಾ ಇತಿಹಾಸ',
    nav_products: 'ಉತ್ಪನ್ನ ಡೇಟಾಬೇಸ್',
    nav_rules: 'ಕಾಯಿದೆಗಳು & ನಿಯಮಗಳು',
    nav_font_size: 'ಮಾಪನ ಕೇಂದ್ರ',
    nav_analytics: 'ವರದಿಗಳು & ವಿಶ್ಲೇಷಣೆ',
    nav_help: 'ಸಹಾಯ & ಸಂಪನ್ಮೂಲಗಳು',
    nav_more_tools: 'ಹೆಚ್ಚಿನ ಪರಿಕರಗಳು',
    nav_specialized_labs: 'ವಿಶೇಷ ಮಾಪನ ಪ್ರಯೋಗಾಲಯಗಳು',
    nav_labeltruth: 'ಲೇಬಲ್‌ಟ್ರೂತ್™ ಕ್ರಾಸ್-ವ್ಯೂ',
    nav_labeltruth_desc: 'ನಿಯಮ 18(2) ಡ್ಯುಯಲ್ MRP ಪರಿಶೀಲನೆ',
    nav_active_inspection: 'ಸಕ್ರಿಯ ತಪಾಸಣೆ',
    nav_active_inspection_desc: 'ಲೇಬಲ್ ಪರಿಹಾರ',
    nav_fingerprint: 'ಅನುಸರಣೆ ಫಿಂಗರ್‌ಪ್ರಿಂಟ್',
    nav_fingerprint_desc: 'ವ್ಯತ್ಯಾಸ ಗುರುತಿಸುವಿಕೆ',
    nav_spectrashield: 'ಸ್ಪೆಕ್ಟ್ರಾಶೀಲ್ಡ್™ UV/NIR',
    nav_spectrashield_desc: 'ಫೋರೆನ್ಸಿಕ್ಸ್ ತಪಾಸಣೆ',
    nav_settings: 'ಅಧಿಕಾರಿ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    nav_settings_desc: 'ವ್ಯಾಪ್ತಿ ಮತ್ತು ಆದ್ಯತೆಗಳು',
    dashboard_welcome: 'ಕಾನೂನು ಮಾಪನಶಾಸ್ತ್ರ ತಪಾಸಣೆ ಮತ್ತು ಜಾರಿ ಪೋರ್ಟಲ್',
    dashboard_sub: 'ಪ್ಯಾಕ್ ಮಾಡಿದ ಸರಕುಗಳ ನಿಯಮಗಳು 2011 ರ ಅಡಿಯಲ್ಲಿ ಕಾನೂನುಬದ್ಧ ಪರಿಶೀಲನೆ ನಡೆಸಿ.',
    motto_title: 'ರಾಷ್ಟ್ರೀಯ ಜಾರಿ ಧ್ಯೇಯವಾಕ್ಯ',
    motto_text: '"ನಿಖರ ಅಳತೆ, ನ್ಯಾಯಯುತ ರಾಷ್ಟ್ರ ನಿರ್ಮಾಣ"',
    motto_dept: 'ಗ್ರಾಹಕ ವ್ಯವಹಾರಗಳ ಇಲಾಖೆ • ಭಾರತ ಸರ್ಕಾರ',
    stat_total_inspections: 'ಒಟ್ಟು ತಪಾಸಣೆಗಳು',
    stat_compliant: 'ನಿಯಮಾನುಸಾರ ಪ್ಯಾಕೇಜ್‌ಗಳು',
    stat_violations: 'ಉಲ್ಲಂಘನೆ / ವಶಪಡಿಸಿಕೊಳ್ಳುವಿಕೆ',
    stat_confidence: 'ಮಾಪನಶಾಸ್ತ್ರ ನಿಖರತೆ',
    capture_location: 'ಪ್ರಸ್ತುತ ಸ್ಥಳವನ್ನು ಸೆರೆಹಿಡಿಯಿರಿ',
    capturing: 'GPS ಪಡೆಯಲಾಗುತ್ತಿದೆ...',
    open_gmaps: 'ಗೂಗಲ್ ಮ್ಯಾಪ್ಸ್‌ನಲ್ಲಿ ತೆರೆಯಿರಿ',
    copy_coords: 'ನಿರ್ದೇಶಾಂಕಗಳನ್ನು ನಕಲಿಸಿ',
    copied: 'ನಕಲಿಸಲಾಗಿದೆ!',
    geotag_title: 'ಸಂಸ್ಥೆಯ ಸ್ಥಳ & ಜಿಯೋ-ಟ್ಯಾಗ್',
    shop_address: 'ಅಂಗಡಿ / ಸಂಸ್ಥೆಯ ಪೂರ್ಣ ವಿಳಾಸ',
    district: 'ಜಿಲ್ಲೆ',
    state: 'ರಾಜ್ಯ',
    pin_code: 'ಪಿನ್ ಕೋಡ್',
    generate_report: 'ಅಧಿಕೃತ ವರದಿ ರಚಿಸಿ',
    reset: 'ಮರುಹೊಂದಿಸಿ',
    view_unified: 'ಏಕೀಕೃತ ವರದಿ (ಸಿಂಗಲ್ PDF)',
    print_pdf: 'ಪ್ರಮಾಣಪತ್ರ ಮುದ್ರಿಸಿ (PDF)',
    export_json: 'ಡೇಟಾ ರಫ್ತು (JSON)',
    settings_title: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    language_select: 'ಭಾಷೆ (Language)',
    status_compliant: 'ಅನುಸರಿಸಲಾಗಿದೆ',
    status_violation: 'ಉಲ್ಲಂಘನೆ',
    status_review: 'ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ',
    select_language: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
  },

  gu: {
    // Gujarati
    dept_name_hi: 'उपभोक्ता मामले विभाग',
    dept_name_en: 'DEPARTMENT OF CONSUMER AFFAIRS',
    ministry_name: 'ગ્રાહક બાબતો, ખાદ્ય અને જાહેર વિતરણ મંત્રાલય',
    division_name: 'લીગલ મેટ્રોલોજી વિભાગ (Legal Metrology)',
    portal_title: 'પક્ષ્ય (PAKSHYA)',
    portal_version: 'પોર્ટલ V2.6',
    portal_subtitle: 'લીગલ મેટ્રોલોજી એન્ફોર્સમેન્ટ સિસ્ટમ',
    helpline_title: 'રાષ્ટ્રીય ગ્રાહક હેલ્પલાઇન',
    toll_free: '(ટોલ-ફ્રી)',
    nav_dashboard: 'ડેશબોર્ડ',
    nav_new_inspection: 'નવું નિરીક્ષણ',
    nav_history: 'નિરીક્ષણ ઇતિહાસ',
    nav_products: 'ઉત્પાદન ડેટાબેઝ',
    nav_rules: 'કાયદા અને નિયમો',
    nav_font_size: 'મેટ્રોલોજી સ્ટેશન',
    nav_analytics: 'અહેવાલો અને વિશ્લેષણ',
    nav_help: 'મદદ અને સંસાધનો',
    nav_more_tools: 'વધુ સાધનો',
    nav_specialized_labs: 'વિશેષ મેટ્રોલોજી લેબ્સ',
    nav_labeltruth: 'લેબલટ્રુથ™ ક્રોસ-વ્યૂ',
    nav_labeltruth_desc: 'નિયમ 18(2) ડ્યુઅલ MRP ચકાસણી',
    nav_active_inspection: 'સક્રિય નિરીક્ષણ',
    nav_active_inspection_desc: 'અસ્પષ્ટ લેબલ ઉકેલ',
    nav_fingerprint: 'અનુપાલન ફિંગરપ્રિન્ટ',
    nav_fingerprint_desc: 'શ્રિંકફ્લેશન તફાવતો',
    nav_spectrashield: 'સ્પેક્ટ્રાશીલ્ડ™ UV/NIR',
    nav_spectrashield_desc: 'ફોરેન્સિક્સ તપાસ',
    nav_settings: 'અધિકારી સેટિંગ્સ',
    nav_settings_desc: 'અધિકારક્ષેત્ર અને પસંદગીઓ',
    dashboard_welcome: 'લીગલ મેટ્રોલોજી નિરીક્ષણ અને અમલીકરણ પોર્ટલ',
    dashboard_sub: 'પેકેજ્ડ કોમોડિટીઝ નિયમો, 2011 હેઠળ કાનૂની પાલનની ચકાસણી કરો.',
    motto_title: 'રાષ્ટ્રીય અમલીકરણ સૂત્ર',
    motto_text: '"ચોક્કસ માપ, ન્યાયી રાષ્ટ્રનું નિર્માણ"',
    motto_dept: 'ગ્રાહક બાબતોનો વિભાગ • ભારત સરકાર',
    stat_total_inspections: 'કુલ નિરીક્ષણો',
    stat_compliant: 'સુસંગત પેકેજો',
    stat_violations: 'ઉલ્લંઘન / જપ્તી',
    stat_confidence: 'મેટ્રોલોજી સચોટતા',
    capture_location: 'વર્તમાન સ્થાન મેળવો',
    capturing: 'GPS મેળવી રહ્યું છે...',
    open_gmaps: 'ગૂગલ મેપ્સમાં જુઓ',
    copy_coords: 'કોઓર્ડિનેટ્સ કૉપિ કરો',
    copied: 'કૉપિ થઈ ગયું!',
    geotag_title: 'પેઢીનું સ્થાન અને જીઓ-ટેગ',
    shop_address: 'દુકાન / પેઢીનું પૂરું સરનામું',
    district: 'જિલ્લો',
    state: 'રાજ્ય',
    pin_code: 'પિન કોડ',
    generate_report: 'સત્તાવાર અહેવાલ બનાવો',
    reset: 'રીસેટ કરો',
    view_unified: 'સંકલિત અહેવાલ (સિંગલ PDF)',
    print_pdf: 'પ્રમાણપત્ર પ્રિન્ટ કરો (PDF)',
    export_json: 'ડેટા નિકાસ (JSON)',
    settings_title: 'સેટિંગ્સ',
    language_select: 'ભાષા (Language)',
    status_compliant: 'સુસંગત',
    status_violation: 'ઉલ્લંઘન',
    status_review: 'સમીક્ષા હેઠળ',
    select_language: 'ભાષા પસંદ કરો',
  }
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, fallback?: string) => string;
  supportedLanguages: LanguageOption[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>('en');

  useEffect(() => {
    try {
      const saved = localStorage.getItem('pakshya_language') as LanguageCode | null;
      if (saved && TRANSLATIONS[saved]) {
        setLanguageState(saved);
      }
    } catch {
      // localStorage not accessible
    }
  }, []);

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('pakshya_language', lang);
      document.documentElement.lang = lang;
    } catch {
      // localStorage not accessible
    }
  };

  const t = (key: string, fallback?: string): string => {
    const langDict = TRANSLATIONS[language];
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    // Fallback to English
    const enDict = TRANSLATIONS['en'];
    if (enDict && enDict[key]) {
      return enDict[key];
    }
    // Fallback to provided default or key
    return fallback !== undefined ? fallback : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, supportedLanguages: SUPPORTED_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      language: 'en',
      setLanguage: () => {},
      t: (key: string, fallback?: string) => fallback || key,
      supportedLanguages: SUPPORTED_LANGUAGES,
    };
  }
  return context;
};
